name: PhantomSMP
version: 7.0.0
main: com.phantom.smp.PhantomSMP
api-version: 1.21
author: PhantomDev
description: Ultimate Phantom SMP Plugin with 3-Level Book System & Trade Animation

commands:
  smpstart:
    description: Start SMP timer with auto grace period
    usage: /smpstart <seconds>
    permission: phantomsmp.admin
  grace:
    description: Start grace period
    usage: /grace <seconds>
    permission: phantomsmp.admin
  givebook:
    description: Give magical book to player
    usage: /givebook <player> [bookname]
    permission: phantomsmp.admin
  giveall:
    description: Give random book to all online players
    usage: /giveall
    permission: phantomsmp.admin
  getallbooks:
    description: Get all 30 Phantom Books
    usage: /getallbooks
    permission: phantomsmp.admin
  booklist:
    description: View all available books
    usage: /booklist
    permission: phantomsmp.use
  bookinfo:
    description: View detailed info about your book
    usage: /bookinfo
    permission: phantomsmp.use
  levelbook:
    description: Open level management GUI
    usage: /levelbook
    permission: phantomsmp.admin
  randombook:
    description: Give random magical book to player
    usage: /randombook <player>
    permission: phantomsmp.admin
  reloadphantom:
    description: Reload PhantomSMP plugin
    usage: /reloadphantom
    permission: phantomsmp.admin
  trade:
    description: Exchange books with another player
    usage: /trade
    permission: phantomsmp.use
  self-trade:
    description: Give your book to another player
    usage: /self-trade
    permission: phantomsmp.use

permissions:
  phantomsmp.admin:
    description: Admin permissions for PhantomSMP
    default: op
  phantomsmp.use:
    description: Use PhantomSMP books and commands
    default: true
