name: SMPStarter
version: 1.0.0
main: com.yourname.smpstarter.SMPStarter
api-version: 1.21
author: YourName
description: Magical SMP Starter Plugin with cinematic effects

commands:
  smpstart:
    description: Start SMP timer
    usage: /smpstart <seconds>
    permission: smpstarter.admin
  givebook:
    description: Give magical book to player
    usage: /givebook <player> [bookname]
    permission: smpstarter.admin
  randombook:
    description: Give random magical book to player
    usage: /randombook <player>
    permission: smpstarter.admin

permissions:
  smpstarter.admin:
    description: Admin permissions for SMPStarter
    default: op
