name: PhantomSMP
version: 4.0.0
main: com.phantom.smp.PhantomSMP
api-version: 1.21
author: PhantomDev
description: Epic Phantom SMP Plugin with Magical Books

commands:
  smpstart:
    description: Start SMP timer with auto grace period
    usage: /smpstart <seconds>
    permission: phantomsmp.admin
  grace:
    description: Start grace period
    usage: /grace <seconds>
    permission: phantomsmp.admin
  givebook:
    description: Give magical book to player
    usage: /givebook <player> [bookname]
    permission: phantomsmp.admin
  giveall:
    description: Give random book to all online players
    usage: /giveall
    permission: phantomsmp.admin
  booklist:
    description: View all available books
    usage: /booklist
    permission: phantomsmp.use
  randombook:
    description: Give random magical book to player
    usage: /randombook <player>
    permission: phantomsmp.admin
  reloadphantom:
    description: Reload PhantomSMP plugin
    usage: /reloadphantom
    permission: phantomsmp.admin

permissions:
  phantomsmp.admin:
    description: Admin permissions for PhantomSMP
    default: op
  phantomsmp.use:
    description: Use PhantomSMP books and commands
    default: true
