name: PhantomSMP
version: 1.0.0
main: com.minetwice.phantomsmp.PhantomSMP
api-version: 1.21
author: MineTwice

commands:
  smpstart:
    description: Start the SMP
    usage: /smpstart
    permission: phantomsmp.admin
  smprewind:
    description: Reset all books
    usage: /smprewind
    permission: phantomsmp.admin
  bookgive:
    description: Give a book
    usage: /bookgive <player> <book>
    permission: phantomsmp.admin
  bookinfo:
    description: View book info
    usage: /bookinfo
    permission: phantomsmp.admin

permissions:
  phantomsmp.admin:
    default: op
